### ISSUE TITLE
모든 R, RMD 파일에 init.R 추가해주세요.

### ISSUE THREAD

**Issue by skysign** [skysign/KoreaAddressAPI#11]
프로젝트 전체적으로 초기화에 사용할 파일을 추가했습니다.
모든 R, RMD 파일에 init.R 추가해주세요.

```
# Initialize
source(file.path(getwd(), "01 common", "init.R"))
```

참고 : https://github.com/skysign/KoreaAddressAPI/blob/master/30%20Analysis/unittest/unitest.R

@seongilp @borajeong88 @lady-mama

**Comment by skysign** [comment]
init.R 추가하는 부분은, 잠시 보류하겠습니다.
좀 더 확인해볼 부분이 있습니다.

**Comment by lady-mama** [comment]
네.
