### ISSUE TITLE
20 Assess 에서 data/JiBeon_Korea.csv 파일을 사용해 주세요.

### ISSUE THREAD

**Issue by skysign** [skysign/KoreaAddressAPI#22]
20 Assess 에서 data/JiBeon_Korea.csv 파일을 사용해 주세요.

- 컬럼 이름도 V1 에서 GwanRiBeonHo 와 같이 변경 되어습니다.

@seongilp 

아래 커밋 참고하세요
https://github.com/skysign/KoreaAddressAPI/commit/58789999e91b385328405a1e4ece6175c6df1cad

**Comment by seongilp** [comment]
반영 완료

**Comment by skysign** [comment]
^^)-b

2020년 6월 9일 (화) 오전 10:42, Seongil Park <notifications@github.com>님이 작성:
