### ISSUE TITLE
DESCRIPTION 파일에 들어갈, 영문이름과 이메일 주소 알려주세요

### ISSUE THREAD

**Issue by skysign** [skysign/KoreaAddressAPI#25]
R Package만드는 작업을 하고 있습니다.
패키지의 Author 로 등록할 영문이름과 이메일주소 알려주세요.
https://github.com/skysign/KoreaAddressAPI/blob/master/DESCRIPTION

@borajeong88 @seongilp @JayoungKim82 @lady-mama

**Comment by seongilp** [comment]
Seongil Park, zihado@gmail.com 입니다!

**Comment by JayoungKim82** [comment]
Kim, Jayoung . jayoung82.kim@gmail.com 입니다... 고맙습니다 ^^

**Comment by skysign** [comment]
@lady-mama @borajeong88  영문이름, 이메일주소 알려주세요~

**Comment by lady-mama** [comment]
Moon S. Kim 입니다.
    On Saturday, June 13, 2020, 12:55:43 PM GMT+9, ByeongKeon Kim <notifications@github.com> wrote:  
 
 


@lady-mama @borajeong88 영문이름, 이메일주소 알려주세요~

**Comment by borajeong88** [comment]
Bora Jeong, borajeong88@gmail.com 입니다. 늦어서 죄송합니다:)

**Comment by skysign** [comment]
https://github.com/skysign/KoreaAddressAPI/blob/master/DESCRIPTION
https://github.com/skysign/KoreaAddressAPI/blob/master/_pkgdown.yml

위의 2파일에 영문이름, 이메일주소, 홈페이지(github 주소)로 업데이트 했습니다.
확인해보세요~
